### ISSUE TITLE
"Unknown error occurred"

### ISSUE THREAD

**Issue by kengruven** [rrooggiieerr/homeassistant-nad#3]
I installed this on my HAOS install via HACS, and when I "ADD INTEGRATION" and choose NAD, and select my serial port and "SUBMIT", it just says "Unknown error occurred".

I tried every serial port option, just in case my USB->RS232 breakout box was mislabeled.

I've got a T747, and I also tried connecting to my T535, with identical results.  I looked in all their on-screen menus and didn't see anything related to RS232 control which needed enabling.

On the HA page, Settings -> Devices & services -> HACS -> 2 services -> NAD page, under Logbook, it says "No logbook events found".  That's the only logging/NAD-related page I've found.

I'm new to HA -- how does one troubleshoot this?  Thanks!

**Comment by kengruven** [comment]
I connected my USB->RS232 breakout to my Linux workstation (stock Debian, not HAOS), and downloaded the [joopert/nad_receiver](https://github.com/joopert/nad_receiver) Python library.  I tried connecting that way, and it works:

```
>>> from nad_receiver import *
>>> r = NADReceiver("/dev/ttyUSB0")
>>> r.main_volume('?')
-27.0
>>> r.main_volume('=', -24)
-24.0
```

(Pretty cool!)  So the hardware, cables, and low-level library all seem to be working.  The issue must be in HA, HAOS, the integration, or my config (user error).

**Comment by rrooggiieerr** [comment]
Hi! I developed this integration for my T755 and also use it for a T757, I have not tested it with other devices.

To give me a better understanding what's going on could you enable debugging for the NAD integration, try adding the integration again and report back to me the logging.

You can go to http://homeassistant.local:8123/config/integrations/integration/nad and click _Enable debug logging_ to enable logging

**Comment by kengruven** [comment]
Sure, I’ll do that when I get the chance.

BTW, while power works fine with `nad_receiver`, mute and some other features have issues with that underlying library, so depending on what exactly this integration does on startup, that could be related:

joopert/nad_receiver#60

(I hope I’m remembering the correct syntax for cross-repo bug reports!)

**Comment by kengruven** [comment]
> You can go to http://homeassistant.local:8123/config/integrations/integration/nad and click _Enable debug logging_ to enable logging

I don't see any "Enable debug logging" on that page.  Where exactly should I look?

**Comment by rrooggiieerr** [comment]
<img width="318" alt="Screenshot 2024-10-26 at 20 01 18" src="https://github.com/user-attachments/assets/1f620850-50c6-40f5-84c4-4d0fac253878">

**Comment by rrooggiieerr** [comment]
Maybe you need to enable Advanced mode in your user profile

**Comment by kengruven** [comment]
I enabled Advanced mode (and even logged out and logged in again), but no change here.  Possibly relevant: "Enable debug logging" in the same relative place was already visible for "HACS" before making this change.

Anyway, this is getting off-track for a bug report, and I'm clearly out of my depths with HA in general.  I'll find the HA chat/forums and see if I can get some remedial help there.

**Comment by rrooggiieerr** [comment]
Ok, so maybe the debug option is only there when you have a device added, which you don't because adding your device fails.

You can always add debugging to your `configuration.yaml`:
```
logger:
  default: info
  logs:
    custom_components.nad: debug
    nad_receiver: debug
```

**Comment by kengruven** [comment]
OK, I added that to my `configuration.yaml` and rebooted.  When I try to add my device in the NAD integration page and click "Submit", I see this item in the main logs:

```
Traceback (most recent call last):
  File "/config/custom_components/nad/config_flow.py", line 194, in validate_input_setup_serial
    model = self.exec_command("Main.Model", "?")
            ^^^^^^^^^^^^^^^^^
AttributeError: 'NADReceiverConfigFlow' object has no attribute 'exec_command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nad/config_flow.py", line 120, in async_step_setup_serial
    title, data, options = await self.validate_input_setup_serial(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nad/config_flow.py", line 195, in validate_input_setup_serial
    except (serial.SerialException, CommandNotSupportedError):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'CommandNotSupportedError' is not defined
```

**Comment by kengruven** [comment]
I need to wait for a new "release" (after 0.0.2) to get this on HACS, right?

The `exec_command` issue still needs to be fixed, too, and it's less obvious to me how to fix that.  Suggestions welcome.
